## Упражнения по библиотеке Numpy

In [5]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [13]:
random_array = np.random.randint(0, 10, size=10) 
print("Исходный массив:", random_array)

condition = (random_array > 3) & (random_array < 8)

random_array[condition] = -random_array[condition]

print("Массив после изменения знака:", random_array)

Исходный массив: [2 2 1 4 6 0 4 5 8 5]
Массив после изменения знака: [ 2  2  1 -4 -6  0 -4 -5  8 -5]


**2.** Заменить максимальный элемент случайного массива на 0

In [15]:
import numpy as np

# 1. Создаем случайный массив (для примера)
# np.random.seed(42) # Для воспроизводимости результата
random_array = np.random.randint(1, 20, size=10) # Массив целых чисел от 1 до 19, размер 10
print("Исходный массив:", random_array)

max_element = random_array.max()
print("Максимальный элемент:", max_element)

max_index = random_array.argmax() 

random_array[max_index] = 0

print("Массив после замены максимального элемента на 0:", random_array)

Исходный массив: [ 7 18  6  6 17 11  6  6  3 13]
Максимальный элемент: 18
Массив после замены максимального элемента на 0: [ 7  0  6  6 17 11  6  6  3 13]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [24]:
import itertools

array_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Исходный двумерный массив (список списков):", array_2d)

direct_product = list(itertools.product(*array_2d))

print("Прямое произведение массивов (все комбинации):")
print(direct_product)

array_2d_str = [['A', 'B'], ['X', 'Y', 'Z']]
print("\nИсходный двумерный массив (строки):", array_2d_str)
direct_product_str = list(itertools.product(*array_2d_str))
print("Прямое произведение массивов (строки):")
print(direct_product_str)

Исходный двумерный массив (список списков): [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Прямое произведение массивов (все комбинации):
[(1, 4, 7), (1, 4, 8), (1, 4, 9), (1, 5, 7), (1, 5, 8), (1, 5, 9), (1, 6, 7), (1, 6, 8), (1, 6, 9), (2, 4, 7), (2, 4, 8), (2, 4, 9), (2, 5, 7), (2, 5, 8), (2, 5, 9), (2, 6, 7), (2, 6, 8), (2, 6, 9), (3, 4, 7), (3, 4, 8), (3, 4, 9), (3, 5, 7), (3, 5, 8), (3, 5, 9), (3, 6, 7), (3, 6, 8), (3, 6, 9)]

Исходный двумерный массив (строки): [['A', 'B'], ['X', 'Y', 'Z']]
Прямое произведение массивов (строки):
[('A', 'X'), ('A', 'Y'), ('A', 'Z'), ('B', 'X'), ('B', 'Y'), ('B', 'Z')]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [33]:
A = np.random.randint(0, 10, size=(8, 3))
B = np.random.randint(0, 5, size=(2, 2))

print("Массив A (8x3):")
print(A)
print("\nМассив B (2x2):")
print(B)

sets_B = [set(row) for row in B]

matching_rows_A = []

for row_A in A:
    set_row_A = set(row_A)
    
    contains_all_B_rows = True
    
    for set_row_B in sets_B:
        if not set_row_A.issuperset(set_row_B):
            contains_all_B_rows = False
            break 
            
    if contains_all_B_rows:
        matching_rows_A.append(row_A)

print("\nСтроки в A, которые содержат элементы из каждой строки в B:")
if matching_rows_A:
    for row in matching_rows_A:
        print(row)
else:
    print("Таких строк в массиве A не найдено.")

Массив A (8x3):
[[9 7 4]
 [0 6 3]
 [8 7 9]
 [4 5 7]
 [8 1 1]
 [4 4 0]
 [6 3 2]
 [5 2 4]]

Массив B (2x2):
[[3 0]
 [0 0]]

Строки в A, которые содержат элементы из каждой строки в B:
[0 6 3]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [38]:
matrix_10x3 = np.random.randint(1, 4, size=(10, 3)) 
matrix_10x3[1] = [2, 2, 2]
matrix_10x3[5] = [3, 3, 3]
matrix_10x3[8] = [1, 1, 1]

print("Исходная матрица (10x3):")
print(matrix_10x3)

filtered_rows = []

for row in matrix_10x3:
    if len(set(row)) > 1:
        filtered_rows.append(row)

filtered_matrix = np.array(filtered_rows)

print("\nМатрица со строками из неравных значений:")
print(filtered_matrix)

Исходная матрица (10x3):
[[2 1 3]
 [2 2 2]
 [1 1 3]
 [3 1 3]
 [2 2 3]
 [3 3 3]
 [2 2 2]
 [2 2 3]
 [1 1 1]
 [2 3 3]]

Матрица со строками из неравных значений:
[[2 1 3]
 [1 1 3]
 [3 1 3]
 [2 2 3]
 [2 2 3]
 [2 3 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [40]:
original_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3], 
    [7, 8, 9],
    [4, 5, 6], 
    [10, 11, 12],
    [1, 2, 3]  
])

print("Исходный двумерный массив:")
print(original_array)

unique_rows_array = np.unique(original_array, axis=0)

print("\nМассив после удаления повторяющихся строк:")
print(unique_rows_array)

Исходный двумерный массив:
[[ 1  2  3]
 [ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]
 [ 1  2  3]]

Массив после удаления повторяющихся строк:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [7]:
import time

In [9]:
def product_of_nonzero_diagonal_no_numpy(matrix):
    product = 1
    rows = len(matrix)
    cols = len(matrix[0]) if rows > 0 else 0
    
    for i in range(min(rows, cols)):
        element = matrix[i][i]
        if element != 0:
            product *= element
    return product

X_list = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print(f"Матрица X (список списков):\n{X_list}")
start_time = time.time()
result_no_numpy = product_of_nonzero_diagonal_no_numpy(X_list)
end_time = time.time()
print(f"Произведение ненулевых элементов на диагонали: {result_no_numpy}")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")

X_list_2 = [[1, 2, 3, 4], [5, 6, 0, 8], [9, 10, 11, 12]]
print(f"\nМатрица X_2 (список списков):\n{X_list_2}")
start_time_large = time.time()
result_no_numpy_2 = product_of_nonzero_diagonal_no_numpy(X_list_2)
end_time_large = time.time()
print(f"Произведение ненулевых элементов на диагонали: {result_no_numpy_2}") 
print(f"Время выполнения: {end_time_large - start_time_large:.6f} секунд")

Матрица X (список списков):
[[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
Произведение ненулевых элементов на диагонали: 3
Время выполнения: 0.000136 секунд

Матрица X_2 (список списков):
[[1, 2, 3, 4], [5, 6, 0, 8], [9, 10, 11, 12]]
Произведение ненулевых элементов на диагонали: 66
Время выполнения: 0.000138 секунд


In [11]:
def product_of_nonzero_diagonal_numpy(matrix_np):

    diagonal_elements = np.diag(matrix_np)
    
    nonzero_diagonal_elements = diagonal_elements[diagonal_elements != 0]
    
    return np.prod(nonzero_diagonal_elements)

X_np = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
start_time = time.time()
result_numpy = product_of_nonzero_diagonal_numpy(X_np)
end_time = time.time()
print(f"Произведение ненулевых элементов на диагонали: {result_numpy}")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")

X_np_2 = np.array([[1, 2, 3, 4], [5, 6, 0, 8], [9, 10, 11, 12]])
print(f"\nМатрица X_2 (numpy array):\n{X_np_2}")
start_time_large = time.time()
result_numpy_2 = product_of_nonzero_diagonal_numpy(X_np_2)
end_time_large = time.time()
print(f"Произведение ненулевых элементов на диагонали: {result_numpy_2}") 
print(f"Время выполнения: {end_time_large - start_time_large:.6f} секунд")

Произведение ненулевых элементов на диагонали: 3
Время выполнения: 0.000242 секунд

Матрица X_2 (numpy array):
[[ 1  2  3  4]
 [ 5  6  0  8]
 [ 9 10 11 12]]
Произведение ненулевых элементов на диагонали: 66
Время выполнения: 0.000102 секунд


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [13]:
import random

In [15]:
def check_multiset_no_numpy(x_list, y_list):
    return sorted(x_list) == sorted(y_list)

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(f"Вектор x (список): {x}")
print(f"Вектор y (список): {y}")

start_time = time.time()
result_no_numpy = check_multiset_no_numpy(x, y)
end_time = time.time()
print(f"Задают ли одно и то же мультимножество: {result_no_numpy}")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")

Вектор x (список): [1, 2, 2, 4]
Вектор y (список): [4, 2, 1, 2]
Задают ли одно и то же мультимножество: True
Время выполнения: 0.000066 секунд


In [17]:
def check_multiset_numpy(x_np, y_np):
    return np.array_equal(np.sort(x_np), np.sort(y_np))

x_np = np.array([1, 2, 2, 4])
y_np = np.array([4, 2, 1, 2])
print(f"\nВектор x (numpy): {x_np}")
print(f"Вектор y (numpy): {y_np}")

start_time = time.time()
result_numpy = check_multiset_numpy(x_np, y_np)
end_time = time.time()
print(f"Задают ли одно и то же мультимножество: {result_numpy}")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")


Вектор x (numpy): [1 2 2 4]
Вектор y (numpy): [4 2 1 2]
Задают ли одно и то же мультимножество: True
Время выполнения: 0.002795 секунд


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [19]:
def find_max_after_zero_no_numpy(x_list):
    elements_after_zero = []
    for i in range(1, len(x_list)):
        if x_list[i-1] == 0:
            elements_after_zero.append(x_list[i])
    
    if not elements_after_zero:
        return None
    return max(elements_after_zero)

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(f"Вектор x (список): {x}")

start_time_ = time.time()
result_no_numpy = find_max_after_zero_no_numpy(x)
end_time_ = time.time()
print(f"Максимальный элемент после нуля: {result_no_numpy}")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")

Вектор x (список): [6, 2, 0, 3, 0, 0, 5, 7, 0]
Максимальный элемент после нуля: 5
Время выполнения: 0.002795 секунд


In [21]:
def find_max_after_zero_numpy(x_np):
    mask_preceded_by_zero = np.concatenate(([False], x_np[:-1] == 0))
    
    elements_to_check = x_np[mask_preceded_by_zero]
    
    if elements_to_check.size == 0:
        return None
    
    return np.max(elements_to_check)

x_np = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(f"\nВектор x (numpy): {x_np}")

start_time = time.time()
result_numpy = find_max_after_zero_numpy(x_np)
end_time = time.time()
print(f"Максимальный элемент после нуля: {result_numpy}")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")


Вектор x (numpy): [6 2 0 3 0 0 5 7 0]
Максимальный элемент после нуля: 5
Время выполнения: 0.000111 секунд


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [23]:
def run_length_encode_no_numpy(x_list):
    if not x_list:
        return [], []

    values = []
    counts = []
    
    current_value = x_list[0]
    current_count = 0
    
    for item in x_list:
        if item == current_value:
            current_count += 1
        else:
            values.append(current_value)
            counts.append(current_count)
            current_value = item
            current_count = 1
    
    values.append(current_value)
    counts.append(current_count)
    
    return values, counts

x_list = [2, 2, 2, 3, 3, 3, 5]
print(f"Вектор x (список): {x_list}")

start_time = time.time()
result_values_no_numpy, result_counts_no_numpy = run_length_encode_no_numpy(x_list)
end_time = time.time()
print(f"Результат RLE: ({result_values_no_numpy}, {result_counts_no_numpy})")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")

Вектор x (список): [2, 2, 2, 3, 3, 3, 5]
Результат RLE: ([2, 3, 5], [3, 3, 1])
Время выполнения: 0.000083 секунд


In [25]:
def run_length_encode_numpy(x_np):
    mask = np.r_[True, x_np[1:] != x_np[:-1]]
    
    values = x_np[mask]
    
    indices_of_starts = np.r_[np.where(mask)[0], x_np.size]
    
    counts = np.diff(indices_of_starts)
    
    return values, counts

x_np = np.array([2, 2, 2, 3, 3, 3, 5])
print(f"\nВектор x (numpy): {x_np}")

start_time = time.time()
result_values_numpy, result_counts_numpy = run_length_encode_numpy(x_np)
end_time = time.time()
print(f"Результат RLE: ({result_values_numpy}, {result_counts_numpy})")
print(f"Время выполнения: {end_time - start_time:.6f} секунд")


Вектор x (numpy): [2 2 2 3 3 3 5]
Результат RLE: ([2 3 5], [3 3 1])
Время выполнения: 0.001129 секунд


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [27]:
import math

In [29]:
def euclidean_distance_no_numpy(x_obj, y_obj):
    distance = 0
    for i in range(len(x_obj)):
        distance += (x_obj[i] - y_obj[i])**2
    return math.sqrt(distance)

def distance_matrix_no_numpy(X_list, Y_list):
    num_X = len(X_list)
    num_Y = len(Y_list)
    
    dist_matrix = [[0.0 for _ in range(num_Y)] for _ in range(num_X)]
    
    for i in range(num_X):
        for j in range(num_Y):
            dist_matrix[i][j] = euclidean_distance_no_numpy(X_list[i], Y_list[j])
    return dist_matrix

num_objects_X = 500
num_objects_Y = 200
num_dimensions = 10

X_test_list = [[np.random.rand() for _ in range(num_dimensions)] for _ in range(num_objects_X)]
Y_test_list = [[np.random.rand() for _ in range(num_dimensions)] for _ in range(num_objects_Y)]

print("--- Реализация без NumPy (чистый Python) ---")
start_time = time.time()
dist_matrix_no_numpy = distance_matrix_no_numpy(X_test_list, Y_test_list)
end_time = time.time()
print(f"Матрица расстояний:\n{dist_matrix_no_numpy[:3][:3]}...") 
print(f"Время выполнения: {end_time - start_time:.6f} секунд")

--- Реализация без NumPy (чистый Python) ---
Матрица расстояний:
[[0.9672421344505862, 1.4026990547892928, 1.487909459479819, 1.1419637335421249, 1.3720423941104387, 1.203566875499646, 1.375478383670686, 1.3987456311855861, 1.2609719363574252, 1.221524877110857, 1.1848738375269547, 1.0327062465920627, 1.3751311562531277, 0.9381648144072519, 0.9172565869645347, 0.884140867151457, 1.009979228850338, 1.4901807131769818, 1.0294048152622621, 1.7785216211533186, 1.0541920921389958, 1.3155722522244087, 1.3941240619827138, 1.4665362473653398, 1.2041729323890806, 1.2412027780527284, 1.327680996560925, 1.38602149358338, 1.1680559808658362, 1.0992448254648808, 0.9980935140016831, 1.4011707352910596, 1.0464449541627867, 0.9246176380470078, 1.1079021447177764, 1.3933160890211942, 1.3894897008882776, 1.3253061199815015, 1.356904859288836, 0.4535932795176996, 0.9458007996486602, 1.4822612705638702, 0.9072758152919674, 1.2417616989213034, 1.24493575049201, 1.6452511316867717, 1.3356125082281212, 1.334

In [31]:
def distance_matrix_numpy_vectorized(X_np, Y_np):
    X_sq_sum = np.sum(X_np**2, axis=1)[:, np.newaxis]
    
    Y_sq_sum = np.sum(Y_np**2, axis=1) 
    
    dot_product = np.dot(X_np, Y_np.T)
    
    squared_distances = X_sq_sum + Y_sq_sum - 2 * dot_product
    
    squared_distances[squared_distances < 0] = 0
    
    return np.sqrt(squared_distances)

X_test_np = np.array(X_test_list)
Y_test_np = np.array(Y_test_list)

print("\n--- Реализация с NumPy (векторизованная) ---")
start_time = time.time()
dist_matrix_numpy = distance_matrix_numpy_vectorized(X_test_np, Y_test_np)
end_time = time.time()
print(f"Матрица расстояний:\n{dist_matrix_numpy[:3,:3]}...") 
print(f"Время выполнения: {end_time - start_time:.6f} секунд")


--- Реализация с NumPy (векторизованная) ---
Матрица расстояний:
[[0.96724213 1.40269905 1.48790946]
 [1.27960293 0.95900051 0.82815108]
 [1.39810836 1.69672146 1.60198951]]...
Время выполнения: 0.044031 секунд


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [100]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [103]:
calorie_stats = np.loadtxt("/Users/anastasiaintyakova/innowise/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [106]:
average_calories = np.mean(calorie_stats) - 60

print(average_calories)

46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [108]:
calorie_stats_sorted = np.sort(calorie_stats)

print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [110]:
median_calories = np.median(calorie_stats)

print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [112]:
for percentile in range(1, 101):  
    value = np.percentile(calorie_stats, percentile)
    if value > 60:
        nth_percentile = percentile
        break

print(f"Наименьший процентиль, превышающий 60 калорий: {nth_percentile}%")

Наименьший процентиль, превышающий 60 калорий: 4%


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [114]:
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100

print(f"{more_calories:.2f}% хлопьев содержат больше 60 калорий на порцию.")

96.10% хлопьев содержат больше 60 калорий на порцию.


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [116]:
calorie_std = np.std(calorie_stats)

print(f"Стандартное отклонение калорий: {calorie_std:.2f}")

Стандартное отклонение калорий: 19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Анализ данных о калорийности различных марок хлопьев показывает, что CrunchieMunchies — действительно уникальный продукт. Среднее количество калорий среди конкурентов составляет около 107, а стандартное отклонение — около 19, что указывает на значительный разброс. Однако CrunchieMunchies содержит всего 60 калорий на порцию — значительно ниже не только среднего значения, но и диапазона, в котором находится большинство продуктов. Более 96% хлопьев на рынке имеют более высокую калорийность. Эти результаты можно эффективно использовать в маркетинге, подчеркивая, что CrunchieMunchies — это низкокалорийный, здоровый выбор для потребителей, стремящихся к правильному питанию без ущерба для вкуса.

In [167]:
# your code